Allow for setting EC2 instance profile
ansible-community/molecule-plugins pull request #164
Opened 2023-06-01 14:37 UTC by Thomas-McKanna

This is a small change, but I think it would be useful for people to be able to set an instance profile if the EC2 instance needs access to other AWS resources, like S3 buckets.

2023-06-06 10:16 UTC, apatard requested changes
Can you please remove the extra space before the colon in the create.yml change ?
(See lint check)

2023-06-08 01:33 UTC, Thomas-McKanna commented
Yes @apatard I will get that change pushed shortly

2023-06-09 13:52 UTC, apatard approved these changes

2023-06-09 13:53 UTC, apatard commented
> Change has been made

Thanks.

2023-06-09 13:54 UTC, merged