docker/create.yml: create network before building local image
ansible-community/molecule-plugins pull request #195
Opened 2023-10-23 20:52 UTC by pbjhelmert

Else the build will attempt to use a network that hasn't been created yet. This is essentially a resurrection of ehartmann's PR against molecule-docker before its death.

Closes: #24

2023-10-24 22:51 UTC, pbjhelmert commented
Seems like the failures are related to an indirect dependency, `pytest_plus`, introducing functionality to fail tests when there are duplicate test names:

https://github.com/pytest-dev/pytest-plus/releases/tag/v0.5.0

I'll just override this for now since these changes are unrelated.

2023-11-13 07:04 UTC, zhan9san requested changes

2023-11-13 07:04 UTC, zhan9san commented on tox.ini
> +    PYTEST_CHECK_TEST_DUPLICATE=0
The duplicate name has been fixed in #197.

Could you please remove this item?

2023-11-13 19:04 UTC, pbjhelmert commented
Done!

2023-11-14 01:40 UTC, zhan9san approved these changes

2023-11-14 01:40 UTC, merged